version: '2'
services:
  test:
    image: reacttt/test-lint
    container_name: reacttt-test-lint
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run docker-test-lint
